server:
  port: 5004

spring:
  application:
    name: service-feign
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5000/eureka/
feign:
  hystrix:
    enabled: true

routing:
  filter-pattern: /*

service:
  eureka-client:
    url-list:
      - http://172.17.6.103:5002
      - http://172.17.6.103:5003
    connectionRequestTimeout: 5000
    connectTimeout: 5000
    readTimeout: 100000
    testConnectTimeout: 1000