server:
  port: 5002

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5000/eureka/
spring:
  application:
    name: eureka-client
