server:
  port: 5005
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5000/eureka/
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: service-zuul
zuul:
  routes:
    eureka-client: /eureka-client/**
    service-ribbon: /service-ribbon/**
    service-feign: /service-feign/**
