server:
  port: 5005
eureka:
  instance:
    hostname: 172.17.6.103
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5000/eureka/
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: service-zuul
zuul:
  routes:
    service-feign:
      path: /service-feign/**
      id: service-feign
#      service-id: service-feign
      url: http://${eureka.instance.hostname}:5004/
      stripPrefix: false
  # 自定义功能，自定义代码判断多个服务的可用性，并路由
  custom-routing:
    test-connect-timeout: 1000
    services:
      eureka-client:
        - http://${eureka.instance.hostname}:5002
        - http://${eureka.instance.hostname}:5003
