server:
  port: 5001

spring:
  application:
    name: boot-admin

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5000/eureka/